# buildspec.yml (located in ecolens-backend folder)
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build --template template.yaml
artifacts:
  files:
    - '**/*'
  base-directory: .aws-sam/build
